# Generated by Django 4.2.6 on 2023-11-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='fleet_pricing',
        ),
        migrations.RemoveField(
            model_name='individualrider',
            name='pricing',
        ),
        migrations.DeleteModel(
            name='PricingStructure',
        ),
    ]
