# Generated by Django 4.2.6 on 2023-11-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone_number_verification_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number_verification_key',
        ),
    ]
