# Generated by Django 4.2.6 on 2023-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_phone_number_verification_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number_verification_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
