# Generated by Django 4.2.6 on 2023-12-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone_number_verification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number_verification_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
