# Generated by Django 4.2.6 on 2024-01-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_is_verified_user_email_verification_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
    ]
