# Generated by Django 4.2.6 on 2024-01-14 12:27

import accounts.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_accept_terms_user_accept_terms_and_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(choices=[('ILORN', 'ILORIN')], default=accounts.enums.OperatingCities['ILORIN'], verbose_name='Business city'),
        ),
    ]
