# Generated by Django 4.2.6 on 2024-01-14 12:36

import accounts.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_business_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(choices=[('ILORIN', 'ILORIN')], default=accounts.enums.OperatingCities['ILORIN'], verbose_name='Business city'),
        ),
    ]
