# Generated by Django 4.2.6 on 2024-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_business_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_key_expires',
            field=models.DateTimeField(null=True, verbose_name='Email key expires at'),
        ),
    ]
