# Generated by Django 4.2.6 on 2024-02-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_password_reset_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_password_reset_link',
            field=models.BooleanField(default=False),
        ),
    ]
